function numberFromEnv(name: string, fallback: number): number {
  const raw = import.meta.env[name]
  const parsed = Number(raw)
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : fallback
}

export const runtimePerformance = {
  network: {
    apiDefaultTimeoutMs: numberFromEnv('VITE_API_DEFAULT_TIMEOUT_MS', 120000),
    legacyApiTimeoutMs: numberFromEnv('VITE_LEGACY_API_TIMEOUT_MS', 30000),
    tauriBackendPollMs: numberFromEnv('VITE_TAURI_BACKEND_POLL_MS', 200),
    tauriBackendWaitMs: numberFromEnv('VITE_TAURI_BACKEND_WAIT_MS', 30000),
    tauriHealthCheckTimeoutMs: numberFromEnv('VITE_TAURI_HEALTH_CHECK_TIMEOUT_MS', 5000),
    shortTaskTimeoutMs: numberFromEnv('VITE_API_SHORT_TASK_TIMEOUT_MS', 30000),
    mediumTaskTimeoutMs: numberFromEnv('VITE_API_MEDIUM_TASK_TIMEOUT_MS', 60000),
    longTaskTimeoutMs: numberFromEnv('VITE_API_LONG_TASK_TIMEOUT_MS', 120000),
    planningTaskTimeoutMs: numberFromEnv('VITE_PLANNING_TASK_TIMEOUT_MS', 300000),
  },
  dagSse: {
    messageThrottleMs: numberFromEnv('VITE_DAG_SSE_MESSAGE_THROTTLE_MS', 100),
    maxQueueSize: numberFromEnv('VITE_DAG_SSE_MAX_QUEUE_SIZE', 50),
    reconnectBaseDelayMs: numberFromEnv('VITE_DAG_SSE_RECONNECT_BASE_DELAY_MS', 1000),
    reconnectMaxDelayMs: numberFromEnv('VITE_DAG_SSE_RECONNECT_MAX_DELAY_MS', 30000),
  },
  autopilotPanel: {
    chapterChunkEmitIntervalMs: numberFromEnv('VITE_AUTOPILOT_CHUNK_EMIT_INTERVAL_MS', 120),
    draftStreamPollMs: numberFromEnv('VITE_AUTOPILOT_DRAFT_STREAM_POLL_MS', 5000),
    writingTypewriterIntervalMs: numberFromEnv('VITE_AUTOPILOT_WRITING_TYPEWRITER_INTERVAL_MS', 30),
    nodeWritingTelemetryPollMs: numberFromEnv('VITE_AUTOPILOT_NODE_TELEMETRY_POLL_MS', 2500),
    terminalScrollUnlockDelayMs: numberFromEnv('VITE_AUTOPILOT_TERMINAL_SCROLL_UNLOCK_DELAY_MS', 220),
    terminalDeskRefreshDebounceMs: numberFromEnv('VITE_AUTOPILOT_TERMINAL_DESK_REFRESH_DEBOUNCE_MS', 300),
    terminalReconnectBaseDelayMs: numberFromEnv('VITE_AUTOPILOT_TERMINAL_RECONNECT_BASE_DELAY_MS', 3000),
    terminalReconnectMaxDelayMs: numberFromEnv('VITE_AUTOPILOT_TERMINAL_RECONNECT_MAX_DELAY_MS', 30000),
    stageTransitionDelayMs: numberFromEnv('VITE_AUTOPILOT_STAGE_TRANSITION_DELAY_MS', 2000),
    daemonHeartbeatGraceSeconds: numberFromEnv('VITE_AUTOPILOT_DAEMON_HEARTBEAT_GRACE_SECONDS', 60),
    chapterStreamContentMaxLength: numberFromEnv('VITE_AUTOPILOT_CHAPTER_STREAM_CONTENT_MAX_LENGTH', 80000),
    toggleThrottleMs: numberFromEnv('VITE_AUTOPILOT_TOGGLE_THROTTLE_MS', 1000),
    stopRequestTimeoutMs: numberFromEnv('VITE_AUTOPILOT_STOP_REQUEST_TIMEOUT_MS', 5000),
    statusFetchTimeoutMs: numberFromEnv('VITE_AUTOPILOT_STATUS_FETCH_TIMEOUT_MS', 10000),
    minChapterStreamRestartMs: numberFromEnv('VITE_AUTOPILOT_STREAM_MIN_RESTART_MS', 3000),
    maxChapterStreamReconnectAttempts: numberFromEnv('VITE_AUTOPILOT_STREAM_MAX_RECONNECT_ATTEMPTS', 5),
    streamReconnectBaseDelayMs: numberFromEnv('VITE_AUTOPILOT_STREAM_RECONNECT_BASE_DELAY_MS', 1000),
    streamReconnectMaxDelayMs: numberFromEnv('VITE_AUTOPILOT_STREAM_RECONNECT_MAX_DELAY_MS', 30000),
    streamIdleReconnectDelayMs: numberFromEnv('VITE_AUTOPILOT_STREAM_IDLE_RECONNECT_DELAY_MS', 1500),
    streamRetryCooldownMultiplier: numberFromEnv('VITE_AUTOPILOT_STREAM_RETRY_COOLDOWN_MULTIPLIER', 4),
    pollRequiresAiReviewMs: numberFromEnv('VITE_AUTOPILOT_POLL_AI_REVIEW_MS', 5000),
    pollManualReviewMs: numberFromEnv('VITE_AUTOPILOT_POLL_MANUAL_REVIEW_MS', 10000),
    pollIdleMs: numberFromEnv('VITE_AUTOPILOT_POLL_IDLE_MS', 3000),
    pollSseConnectedMs: numberFromEnv('VITE_AUTOPILOT_POLL_SSE_CONNECTED_MS', 15000),
    pollRunningMs: numberFromEnv('VITE_AUTOPILOT_POLL_RUNNING_MS', 5000),
    pollMaxMs: numberFromEnv('VITE_AUTOPILOT_POLL_MAX_MS', 120000),
  },
  autopilotDag: {
    statusPollMs: numberFromEnv('VITE_AUTOPILOT_DAG_STATUS_POLL_MS', 7000),
  },
  autopilotMetrics: {
    tensionAutoRefreshSeconds: numberFromEnv('VITE_TENSION_AUTO_REFRESH_SECONDS', 30),
    tensionFetchTimeoutMs: numberFromEnv('VITE_TENSION_FETCH_TIMEOUT_MS', 60000),
    tensionInitialRenderDelayMs: numberFromEnv('VITE_TENSION_INITIAL_RENDER_DELAY_MS', 50),
    tensionRenderRetryDelayMs: numberFromEnv('VITE_TENSION_RENDER_RETRY_DELAY_MS', 200),
    tensionResizeDebounceMs: numberFromEnv('VITE_TENSION_RESIZE_DEBOUNCE_MS', 100),
    tensionRenderDimensionAttemptsMax: numberFromEnv('VITE_TENSION_RENDER_ATTEMPTS_MAX', 40),
    foreshadowPollMs: numberFromEnv('VITE_FORESHADOW_LEDGER_POLL_MS', 30000),
    foreshadowFetchTimeoutMs: numberFromEnv('VITE_FORESHADOW_LEDGER_FETCH_TIMEOUT_MS', 10000),
    voiceDriftPollMs: numberFromEnv('VITE_VOICE_DRIFT_POLL_MS', 30000),
    circuitBreakerPollMs: numberFromEnv('VITE_CIRCUIT_BREAKER_POLL_MS', 10000),
  },
  jobs: {
    statusPollMs: numberFromEnv('VITE_JOB_STATUS_POLL_MS', 3000),
  },
  stats: {
    sidebarClockTickMs: numberFromEnv('VITE_STATS_SIDEBAR_CLOCK_TICK_MS', 60000),
  },
  aiInvocation: {
    generationPollMs: numberFromEnv('VITE_AI_INVOCATION_GENERATION_POLL_MS', 1200),
  },
  feedback: {
    incidentRingCap: numberFromEnv('VITE_FEEDBACK_INCIDENT_RING_CAP', 30),
    dedupeMs: numberFromEnv('VITE_FEEDBACK_DEDUPE_MS', 4500),
    dedupeMaxKeys: numberFromEnv('VITE_FEEDBACK_DEDUPE_MAX_KEYS', 200),
    axiosAggregateSilenceMs: numberFromEnv('VITE_FEEDBACK_AXIOS_AGGREGATE_SILENCE_MS', 520),
    exportBackendMaxLines: numberFromEnv('VITE_FEEDBACK_EXPORT_BACKEND_MAX_LINES', 900),
    exportBackendRingLimit: numberFromEnv('VITE_FEEDBACK_EXPORT_BACKEND_RING_LIMIT', 300),
    actionBackendMaxLines: numberFromEnv('VITE_FEEDBACK_ACTION_BACKEND_MAX_LINES', 700),
    actionBackendRingLimit: numberFromEnv('VITE_FEEDBACK_ACTION_BACKEND_RING_LIMIT', 200),
  },
  workbench: {
    deskReloadDebounceMs: numberFromEnv('VITE_WORKBENCH_DESK_RELOAD_DEBOUNCE_MS', 1100),
    deskTickDebounceMs: numberFromEnv('VITE_WORKBENCH_DESK_TICK_DEBOUNCE_MS', 450),
    deskRefreshEmitDebounceMs: numberFromEnv('VITE_WORKBENCH_DESK_REFRESH_EMIT_DEBOUNCE_MS', 1200),
    storyTreeRefreshDebounceMs: numberFromEnv('VITE_WORKBENCH_STORY_TREE_REFRESH_DEBOUNCE_MS', 200),
    storyTreeMacroProgressPollMs: numberFromEnv('VITE_WORKBENCH_STORY_TREE_MACRO_PROGRESS_POLL_MS', 3200),
    storyTreeMacroPersistRetryAttempts: numberFromEnv('VITE_WORKBENCH_STORY_TREE_MACRO_PERSIST_RETRY_ATTEMPTS', 12),
    storyTreeMacroPersistRetryDelayMs: numberFromEnv('VITE_WORKBENCH_STORY_TREE_MACRO_PERSIST_RETRY_DELAY_MS', 400),
    worldbuildingSavedNoticeMs: numberFromEnv('VITE_WORKBENCH_WORLDBUILDING_SAVED_NOTICE_MS', 8000),
    guardrailSnapshotRefreshDelayMs: numberFromEnv('VITE_WORKBENCH_GUARDRAIL_REFRESH_DELAY_MS', 3500),
    guardrailEmptyBackoffMs: numberFromEnv('VITE_WORKBENCH_GUARDRAIL_EMPTY_BACKOFF_MS', 90000),
    guardrailErrorBackoffMs: numberFromEnv('VITE_WORKBENCH_GUARDRAIL_ERROR_BACKOFF_MS', 60000),
    chapterHintSavedNoticeMs: numberFromEnv('VITE_WORKBENCH_CHAPTER_HINT_SAVED_NOTICE_MS', 2000),
    knowledgeReloadBusyMs: numberFromEnv('VITE_WORKBENCH_KNOWLEDGE_RELOAD_BUSY_MS', 500),
    promptPlazaSelectDelayMs: numberFromEnv('VITE_WORKBENCH_PROMPT_PLAZA_SELECT_DELAY_MS', 400),
    promptPlazaCloseAnimationMs: numberFromEnv('VITE_WORKBENCH_PROMPT_PLAZA_CLOSE_ANIMATION_MS', 200),
  },
  editor: {
    chapterPreviewDebounceMs: numberFromEnv('VITE_EDITOR_CHAPTER_PREVIEW_DEBOUNCE_MS', 300),
    chapterAutosaveMs: numberFromEnv('VITE_EDITOR_CHAPTER_AUTOSAVE_MS', 30000),
    castSearchDebounceMs: numberFromEnv('VITE_EDITOR_CAST_SEARCH_DEBOUNCE_MS', 280),
  },
}
