"""LLM Settings API

提供 LLM 配置的获取和保存接口。
"""
import os
import logging
from typing import Dict, Any, Optional
from pydantic import BaseModel, Field
from fastapi import APIRouter, HTTPException

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/llm-settings", tags=["llm-settings"])


class LLMProviderConfig(BaseModel):
    """LLM Provider Configuration"""
    enabled: bool = True
    api_key: str = ""
    base_url: str = ""
    model: str = ""
    max_tokens: int = Field(default=2048, ge=1, le=8192)
    temperature: float = Field(default=0.7, ge=0.0, le=2.0)
    timeout: int = Field(default=300, ge=10, le=600)


class LLMSettings(BaseModel):
    """Complete LLM Settings"""
    active_provider: str = Field(default="ark", description="当前使用的提供商: anthropic, ark, mock")
    anthropic: LLMProviderConfig = Field(default_factory=lambda: LLMProviderConfig(
        api_key="",
        base_url="https://api.anthropic.com",
        model="claude-3-sonnet-20240229",
        max_tokens=4096,
        temperature=0.7
    ))
    ark: LLMProviderConfig = Field(default_factory=lambda: LLMProviderConfig(
        api_key="",
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        model="qwen-turbo",
        max_tokens=2048,
        temperature=0.7
    ))


def _get_env_path() -> str:
    """Get the .env file path"""
    # Try to find .env in project root
    # Start from current file location and go up to project root
    current_dir = os.path.dirname(os.path.abspath(__file__))
    # interfaces/api/v1/core -> interfaces/api/v1 -> interfaces/api -> interfaces -> project root
    project_root = os.path.abspath(os.path.join(current_dir, "..", "..", "..", ".."))
    env_path = os.path.join(project_root, ".env")
    logger.info(f"Env path resolved to: {env_path}")
    return env_path


def _read_env_file() -> Dict[str, str]:
    """Read current .env file"""
    env_path = _get_env_path()
    env_vars = {}
    
    if os.path.exists(env_path):
        try:
            with open(env_path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        env_vars[key.strip()] = value.strip()
        except Exception as e:
            logger.error(f"Error reading .env file: {e}")
    
    return env_vars


def _write_env_file(env_vars: Dict[str, str]):
    """Write to .env file"""
    env_path = _get_env_path()
    
    try:
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write("# PlotPilot Environment Configuration\n")
            f.write("# Generated by LLM Settings API\n\n")
            
            # Group variables by provider
            groups = {
                "Anthropic": [],
                "Ark/DashScope": [],
                "Other": []
            }
            
            for key, value in sorted(env_vars.items()):
                if key.startswith("ANTHROPIC"):
                    groups["Anthropic"].append((key, value))
                elif key.startswith("ARK"):
                    groups["Ark/DashScope"].append((key, value))
                else:
                    groups["Other"].append((key, value))
            
            # Write Anthropic settings
            if groups["Anthropic"]:
                f.write("# Anthropic Claude Settings\n")
                for key, value in groups["Anthropic"]:
                    f.write(f"{key}={value}\n")
                f.write("\n")
            
            # Write Ark settings
            if groups["Ark/DashScope"]:
                f.write("# Ark/DashScope Settings\n")
                for key, value in groups["Ark/DashScope"]:
                    f.write(f"{key}={value}\n")
                f.write("\n")
            
            # Write other settings
            if groups["Other"]:
                f.write("# Other Settings\n")
                for key, value in groups["Other"]:
                    f.write(f"{key}={value}\n")
    except Exception as e:
        logger.error(f"Error writing .env file: {e}")
        raise


@router.get("", response_model=LLMSettings)
async def get_llm_settings() -> LLMSettings:
    """Get current LLM settings from environment variables"""
    env_vars = _read_env_file()
    
    # Determine active provider
    active_provider = "mock"
    if env_vars.get("ANTHROPIC_API_KEY"):
        active_provider = "anthropic"
    elif env_vars.get("ARK_API_KEY"):
        active_provider = "ark"
    
    settings = LLMSettings(
        active_provider=active_provider,
        anthropic=LLMProviderConfig(
            enabled=bool(env_vars.get("ANTHROPIC_API_KEY")),
            api_key=env_vars.get("ANTHROPIC_API_KEY", ""),
            base_url=env_vars.get("ANTHROPIC_BASE_URL", "https://api.anthropic.com"),
            model=env_vars.get("ANTHROPIC_MODEL", "claude-3-sonnet-20240229"),
            max_tokens=int(env_vars.get("ANTHROPIC_MAX_TOKENS", "4096")),
            temperature=float(env_vars.get("ANTHROPIC_TEMPERATURE", "0.7")),
            timeout=int(env_vars.get("ANTHROPIC_TIMEOUT", "300"))
        ),
        ark=LLMProviderConfig(
            enabled=bool(env_vars.get("ARK_API_KEY")),
            api_key=env_vars.get("ARK_API_KEY", ""),
            base_url=env_vars.get("ARK_BASE_URL", "https://dashscope.aliyuncs.com/compatible-mode/v1"),
            model=env_vars.get("ARK_MODEL", "qwen-turbo"),
            max_tokens=int(env_vars.get("ARK_MAX_TOKENS", "2048")),
            temperature=float(env_vars.get("ARK_TEMPERATURE", "0.7")),
            timeout=int(env_vars.get("ARK_TIMEOUT", "300"))
        )
    )
    
    return settings


@router.post("", response_model=Dict[str, Any])
async def save_llm_settings(settings: LLMSettings) -> Dict[str, Any]:
    """Save LLM settings to .env file"""
    try:
        env_vars = _read_env_file()
        
        # Update Anthropic settings
        if settings.anthropic.api_key:
            env_vars["ANTHROPIC_API_KEY"] = settings.anthropic.api_key
        elif "ANTHROPIC_API_KEY" in env_vars:
            del env_vars["ANTHROPIC_API_KEY"]
        
        env_vars["ANTHROPIC_BASE_URL"] = settings.anthropic.base_url or "https://api.anthropic.com"
        env_vars["ANTHROPIC_MODEL"] = settings.anthropic.model or "claude-3-sonnet-20240229"
        env_vars["ANTHROPIC_MAX_TOKENS"] = str(settings.anthropic.max_tokens)
        env_vars["ANTHROPIC_TEMPERATURE"] = str(settings.anthropic.temperature)
        env_vars["ANTHROPIC_TIMEOUT"] = str(settings.anthropic.timeout)
        
        # Update Ark settings
        if settings.ark.api_key:
            env_vars["ARK_API_KEY"] = settings.ark.api_key
        elif "ARK_API_KEY" in env_vars:
            del env_vars["ARK_API_KEY"]
        
        env_vars["ARK_BASE_URL"] = settings.ark.base_url or "https://dashscope.aliyuncs.com/compatible-mode/v1"
        env_vars["ARK_MODEL"] = settings.ark.model or "qwen-turbo"
        env_vars["ARK_MAX_TOKENS"] = str(settings.ark.max_tokens)
        env_vars["ARK_TEMPERATURE"] = str(settings.ark.temperature)
        env_vars["ARK_TIMEOUT"] = str(settings.ark.timeout)
        
        # Write to file
        _write_env_file(env_vars)
        
        # Also update current process environment
        for key, value in env_vars.items():
            os.environ[key] = value
        
        logger.info(f"LLM settings saved. Active provider: {settings.active_provider}")
        
        return {
            "success": True,
            "message": "设置已保存",
            "active_provider": settings.active_provider
        }
        
    except Exception as e:
        logger.error(f"Failed to save LLM settings: {e}")
        raise HTTPException(status_code=500, detail=f"保存设置失败: {str(e)}")


@router.post("/test", response_model=Dict[str, Any])
async def test_llm_connection(settings: LLMSettings) -> Dict[str, Any]:
    """Test LLM connection with provided settings"""
    try:
        from infrastructure.ai.providers.ark_provider import ArkProvider
        from infrastructure.ai.providers.anthropic_provider import AnthropicProvider
        from infrastructure.ai.config.settings import Settings as AISettings
        from domain.ai.value_objects.prompt import Prompt
        from domain.ai.services.llm_service import GenerationConfig
        
        provider_name = settings.active_provider
        
        if provider_name == "ark":
            if not settings.ark.api_key:
                return {"success": False, "message": "请先配置 Ark API Key"}
            
            ai_settings = AISettings(
                api_key=settings.ark.api_key,
                base_url=settings.ark.base_url
            )
            provider = ArkProvider(ai_settings)
            model = settings.ark.model
            
        elif provider_name == "anthropic":
            if not settings.anthropic.api_key:
                return {"success": False, "message": "请先配置 Anthropic API Key"}
            
            ai_settings = AISettings(
                api_key=settings.anthropic.api_key,
                base_url=settings.anthropic.base_url
            )
            provider = AnthropicProvider(ai_settings)
            model = settings.anthropic.model
            
        else:
            return {"success": True, "message": "Mock 模式无需测试"}
        
        # Test generation
        prompt = Prompt(
            system="You are a helpful assistant.",
            user="Say 'Connection successful' in Chinese."
        )
        config = GenerationConfig(
            model=model,
            max_tokens=50,
            temperature=0.7
        )
        
        import asyncio
        result = await provider.generate(prompt, config)
        
        return {
            "success": True,
            "message": "连接测试成功",
            "response": result.content[:100],
            "provider": provider_name
        }
        
    except Exception as e:
        logger.error(f"LLM connection test failed: {e}")
        return {
            "success": False,
            "message": f"连接测试失败: {str(e)}",
            "provider": settings.active_provider
        }
